version: "3.8"

services:
  producer:
    image: munycha/kafka-producer:1.0.0
    container_name: kafka-producer
    restart: unless-stopped

    environment:
      TZ: Asia/Phnom_Penh
      HOST_FS: /hostfs

    volumes:
      - ./config:/app/config:ro
      - /home/kafkaproducer/test_log_file:/data/input/logs:ro
      - /:/hostfs:ro
